services:
  # Backend API Service
  - type: web
    name: campusspot-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/spots

  # Frontend Static Site
  - type: web
    name: campusspot-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: campusspot-api
          type: web
          property: url
        value: /api
