services:
  # フロントエンドとバックエンドを統合したサービス
  - type: web
    name: campusspot
    env: node
    plan: free
    buildCommand: npm install && npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
